### ISSUE TITLE
Sophisticated Image Processing

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Vein-Toolbox#2]
In Overview:
> Research papers normally apply more sophisticated image processing technique such as the histogram equalization to improve the quality of image however the evaluator may not use such method considering the attack potential required by [BIOPP-Module].

Two questions:
 1. Does this sentence mean that, depending on the attack potential, that "sophisticated image processing" is allowed, or is it always disallowed?
 2. Histogram equalization is available in all sorts of software, including free software, as a one-click operation. While it may be technically sophisticated, it's arguably much simpler than editing freehand, which is allowed. Why is this disallowed?

**Comment by woodbe** [comment]
I only have an answer for question 1 here, which would be that it is due to the attack potential solely. The expectation would be that as we increase the claimed attack potentials this would be included.

As for the second part, I have no idea (it's not something I work with).

**Comment by n-kai** [comment]
@gfiumara 
Use of image processing software is not disallowed (that’s why I use the term “may not”). The evaluator can choose either of methods (pencil or software) to enhance the vein pattern (The toolbox doesn’t require the evaluator to purchase adobe photoshop and spend time to learn how to use it, which may be the best way to enhance the image). Instead she can spend the same amount of time/effort and use a pencil to enhance the vein pattern image. Of course, she can also use the software to do the same level of enhancement by the software but in any case, knowledge or effort required for the such enhancement shall be within the basic attack potential.

Is the following text more clear? (or you can suggest better text)
**If the captured vein pattern image is not clearly visible, the evaluator shall preprocess the image to improve contrast of the vein pattern. The evaluator may use a pencil or image processing software to make the vein pattern clearly visible. The evaluator may use the either of tools, however, the evaluator's effort shall be within the attack potential required by [BIOPP-Module].**

**Comment by gfiumara** [comment]
@n-kai I like that better, yes. To be clear though (since the example was removed), is historgram equalization something that would be disallowed for a basic attack?

**Comment by n-kai** [comment]
Historgram equalization can be done easily using a free software library so it is allowed for a basic attack.

**Comment by woodbe** [comment]
Closed as part of merged changes.
