### ISSUE TITLE
Bad Link on Reference #3

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Vein-Toolbox#4]
I'm getting an Error 403 trying to access Reference 3. [This](https://pdfs.semanticscholar.org/e904/135dd4050b708a6e8a73a8a23b35b53a1053.pdf) appears to be the same document, but is from a PDF harvesting site. Is there a DOI for this reference?

**Comment by woodbe** [comment]
I am seeing the same error when I try to access it as well

**Comment by n-kai** [comment]
I am reviewing the toolboxes and will make a pull request to fix errors including the bad link.

**Comment by woodbe** [comment]
Fixed.
