### ISSUE TITLE
Some suggested normative changes

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Vein-Toolbox#6]
There's a few normative phrases I think may need to change that appear repeatedly in all the toolboxes, but this is the first toolbox I've looked at in depth, so I'm marking it here. These are from the "attacks" documents.

1. > The evaluator shall consider changing the following factors for penetration testing.
   - "Consideration" seems optional to me. If that's the consensus, normative "shall" should be normative "should."

2. > The evaluator can change the creation process, test subject and presentation methods,
   - To my knowledge, "can" isn't normative, change to normative "may?"

3. > If the ST covers multiple configurations for vein unlock, the same test should be performed for all configurations.
    - Should this normative "should" be a "shall?" If there's different modes of operation and one mode is vulnerable, shouldn't that be tested?

**Comment by n-kai** [comment]
I will create a PR that include the following fixes.
1. Replace "shall" with "should".
2. Replace "can" with "may"
3. Replace "should" with "shall" (but mobile devices normally doesn't provide such configuration options. I am not sure for the OS but the developer usually specify only one configuration in the ST to reduce the time for evaluation)

**Comment by woodbe** [comment]
Closing as all toolboxes have been updated with these changes.
